### ISSUE TITLE
Doesn't optimize custom properties

### ISSUE THREAD

**Issue by dizel3d** [css/csso#422] opened 2020-10-04 19:26 UTC
```js
require('csso').minify(text).css
```

where `text` equals
```css
:root {
    --color-controls-type-action-typo-base: rgba(0, 0, 0, 0.1);
    --color-controls-type-action-fill-color-base: rgb(235, 225, 224);
}
```

returns
```css
:root{--color-controls-type-action-typo-base: rgba(0, 0, 0, 0.1);--color-controls-type-action-fill-color-base: rgb(235, 225, 224)}
```

but expected
```css
:root{--color-controls-type-action-typo-base:rgba(0,0,0,.1);--color-controls-type-action-fill-color-base:#ebe1e0}
```

**Comment by dizel3d** [comment] 2020-10-04 19:27
Workaround
```
require('csso').minify(text.replace(/--/g, '____')).css.replace(/____/g, '--')
```

**Comment by lahmatiy** [comment] 2020-11-26 13:49
Duplicate of #425
Merge in #425 since it better express what to do.

**Closed by lahmatiy** 2020-11-26 13:49 UTC
