### ISSUE TITLE
CSSO chokes on css that has already been minified by another minifier

### ISSUE THREAD

**Issue by corbanbrook** [css/csso#185] opened 2014-02-05 17:13 UTC
Error: Please check the validity of the CSS block starting from the line #1912

Sometimes css you compile together might already be minified. CSSO chokes on this content with a random error.

**Comment by jhnns** [comment] 2015-02-03 15:37
CSSO has problems when an end of comment `*/` is followed by an `@` statement like `@import` or `@charset` (https://github.com/css/csso/issues/206#issuecomment-68088979).

CSS preprocessors like SASS usually pull import statements at the beginning so that additional files are instantly downloaded. However, when the preprocessor encounters a bang comment `/*!` with license information, this comment is not removed.

In my particular case it was caused by this css

```css
/*! normalize.css v3.0.2 | MIT License | git.io/normalize */@import url(some/url.css)
```

I've put an empty `a{}` selector between the comment and the `@` and everything was working fine again:

```css
/*! normalize.css v3.0.2 | MIT License | git.io/normalize */a{}@import url(some/url.css)
```

**Comment by lahmatiy** [comment] 2015-10-11 23:54
Needs more details, css example that cause a problem.
I tried

```
/*! normalize.css v3.0.2 | MIT License | git.io/normalize */@import url(some/url.css)
```

No problem with processing.
Closing for now. Re-open if problem still exists.

**Closed by lahmatiy** 2015-10-11 23:54 UTC
