### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by nigelhorne** [css/csso#256] opened 2015-12-03 21:07 UTC
$ npm install -g csso
npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at new ClientRequest (_http_client.js:51:11)
npm ERR!     at TunnelingAgent.exports.request (http.js:31:10)
npm ERR!     at TunnelingAgent.createSocket (/usr/lib/nodejs/tunnel-agent/index.js:117:25)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (/usr/lib/nodejs/tunnel-agent/index.js:184:41)
npm ERR!     at TunnelingAgent.addRequest (/usr/lib/nodejs/tunnel-agent/index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:133:16)
npm ERR!     at Object.exports.request (http.js:31:10)
npm ERR!     at Object.exports.request (https.js:163:15)
npm ERR!     at Request.start (/usr/lib/nodejs/request/index.js:607:30)
npm ERR!     at Request.end (/usr/lib/nodejs/request/index.js:1235:28)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.2.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "csso"
npm ERR! cwd /home/njh
npm ERR! node -v v4.2.2
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/njh/npm-debug.log
npm ERR! not ok code 0

**Comment by lahmatiy** [comment] 2015-12-03 21:11
It's not connected with `csso`.
Looks like you have some troubles with connection or so.

**Comment by nigelhorne** [comment] 2015-12-03 21:36
The connection's fine.  Everything else works.  This is the only program which doesn't.

**Comment by lahmatiy** [comment] 2015-12-08 20:50
I have no idea why you have problem with installation. I even tried it on your `node.js` version (4.2.2), still works to me.
Does it installing without `i` flag? May be you have any suggestions?

**Comment by lahmatiy** [comment] 2016-01-24 21:20
@nigelhorne Does this problem still exist?

**Comment by nigelhorne** [comment] 2016-01-29 15:00
I get this without the -g flag:

# npm install csso
npm WARN install Refusing to install csso as a dependency of itself

**Comment by lahmatiy** [comment] 2016-01-29 15:51
@nigelhorne Probably it's because `name` in `package.json` is `csso`. I found some related questions about this warning for other packages, for example http://stackoverflow.com/questions/27267707/npm-warn-install-refusing-to-install-hapi-as-a-dependency-of-itself

**Comment by lahmatiy** [comment] 2016-02-28 01:11
Closing issue since no more details that can help to reproduce the problem and no confirmation from others.

**Closed by lahmatiy** 2016-02-28 01:11 UTC
Labels: more details needed
