### ISSUE TITLE
Structural optimization fails on browser hacks

### ISSUE THREAD

**Issue by asapach** [css/csso#231] opened 2015-06-20 16:28 UTC
Reproducible on Bootstrap 3.3.5:
```css
.caret {
  border-top: 4px dashed;
  border-top: 4px solid \9;
}
```
Optimized:
```css
.caret {
  border-top: 4px solid \9;
}
```
The IE8 browser hack breaks the other declaration.

**Comment by bc-jasond** [comment] 2015-06-26 19:18
@asapach you beat me to it...  I'm seeing this too

**Comment by jmcmichael** [comment] 2015-07-24 18:18
Same here. Finally tracked the missing Bootstrap caret to CSSO. (Fabulous package otherwise!)

**Comment by emourujarvi** [comment] 2015-08-06 09:33
I also came across this problem. As jmcmichael said, setting structural optimization to false fortunately fixes this problem.

**Comment by lahmatiy** [comment] 2015-10-07 19:16
Fixed by #166

**Comment by tkrotoff** [comment] 2015-10-07 23:02
+1

**Comment by tkrotoff** [comment] 2015-10-08 10:02
@lahmatiy Sure this is fixed? I'm a strong believer in "What ain't tested, ain't working" :) and PR #166 does not include any unit test

```
$ ./bin/csso --version
1.3.12
$ echo ".caret { border-top: 4px dashed; border-top: 4px solid \9; }" > test.css
$ ./bin/csso test.css
.caret{border-top:4px solid \9}
```

The PR integration messed up: look at https://github.com/css/csso/blob/v1.3.12/lib/compressor.js#L125 vs https://github.com/css/csso/pull/166/files#diff-e83fb3368ebbc864f774279d085ac1a8R124

This line from the PR is missing:
```JavaScript
ieHack = (ieReg.test(s.top.s) || ieReg.test(s.right.s) || ieReg.test(s.bottom.s) || ieReg.test(s.left.s));
```

This commit is the cause of this: https://github.com/css/csso/commit/42da5bce11cc1dcc02e72f03d8b617cb63bae5f3#diff-e83fb3368ebbc864f774279d085ac1a8L126

**Comment by lahmatiy** [comment] 2015-10-08 10:16
Thank you for your feedback.
Will investigate issue and add tests this time.

**Comment by lahmatiy** [comment] 2015-10-08 21:07
I see it's another issue now. It's connected with wrong structural optimisation.
Collecting issue #241

**Closed** 2015-10-14 20:31 UTC
Labels: bug
