### ISSUE TITLE
csso 5.0.0 minus value bugs.

### ISSUE THREAD

**Issue by demonguyj** [css/csso#445] opened 2021-12-05 09:48 UTC
Csso 5.0.0 expected value not corrected.

Check it please.

Thanks :)

- Expected
```
<style>
.test {
	margin:0 10px 0 -10px;
        padding:0 10px 0 -10px
}
</style>
```

- csso 5.0.0
```
<style>
.test {
    margin: 0 10px 0-10px;
    padding: 0 10px 0-10px
}
</style>
```

**Comment by lahmatiy** [comment] 2021-12-05 16:40
This is a valid value that any browser can parse. See some details in [CSSTree release notes](https://github.com/csstree/csstree/releases/tag/v2.0.0) about generator

**Comment by lahmatiy** [comment] 2022-07-14 09:42
Closing since that's not a bug but a feature ;)

**Closed** 2022-07-26 14:34 UTC
Labels: won't fix
