### ISSUE TITLE
TypeError: Cannot read property 'isEmpty' of undefined

### ISSUE THREAD

**Issue by peterbe** [css/csso#349] opened 2017-08-25 00:58 UTC
I have a piece of code that uses `csstree`  to turn CSS into an AST. The AST is converted into a plain object, sent to another function that manipulates it (removes some children and mutates some values). Then it comes back, I use `const ast = csstree.fromPlainObject(obj)` to turn it back into an AST object. 

Now, instead of just doing `const css = csstree.translate(ast)` I thought, before I do final delivery of the css string, I'd compress it with `csso` first. Tried this:

```javascript
const obj = cleaned[url]
const cleanedAst = csstree.fromPlainObject(obj)
//console.log(cleanedAst.children);
//
var compressedAst = csso.compress(cleanedAst).ast;  // FAILS
```
To which I get:
```
TypeError: Cannot read property 'isEmpty' of undefined
```

**Comment by peterbe** [comment] 2017-08-25 01:00
As a check, I can walk that ast object of mine. Right after I've used converted it to an AST.
```javascript
const obj = cleaned[url]
const cleanedAst = csstree.fromPlainObject(obj)
csstree.walk(cleanedAst, n => console.log(n))
```

This works and spits out:
```
{ type: 'StyleSheet',
  loc: null,
  children:
   List {
     cursor: null,
     head: { prev: null, next: [Object], data: [Object] },
     tail: { prev: [Object], next: null, data: [Object] } } }
{ type: 'Rule',
  loc: null,
  selector: { type: 'Raw', loc: null, value: '*' },
  block:
   { type: 'Block',
     loc: null,
     children: List { cursor: null, head: [Object], tail: [Object] } } }
{ type: 'Raw', loc: null, value: '*' }
{ type: 'Block',
  loc: null,
  children:
   List {
     cursor: null,
     head: { prev: null, next: null, data: [Object] },
     tail: { prev: null, next: null, data: [Object] } } }
{ type: 'Declaration',
  loc: null,
  important: false,
  property: 'color',
  value: { type: 'Raw', loc: null, value: ' pink ' } }
{ type: 'Raw', loc: null, value: ' pink ' }
{ type: 'Rule',
  loc: null,
  selector: { type: 'Raw', loc: null, value: 'body' },
  block:
   { type: 'Block',
     loc: null,
     children: List { cursor: null, head: [Object], tail: [Object] } } }
{ type: 'Raw', loc: null, value: 'body' }
{ type: 'Block',
  loc: null,
  children:
   List {
     cursor: null,
     head: { prev: null, next: null, data: [Object] },
     tail: { prev: null, next: null, data: [Object] } } }
{ type: 'Declaration',
  loc: null,
  important: false,
  property: 'color',
  value: { type: 'Raw', loc: null, value: ' blue' } }
{ type: 'Raw', loc: null, value: ' blue' }
{ type: 'Rule',
  loc: null,
  selector: { type: 'Raw', loc: null, value: 'p, .navbar' },
  block:
   { type: 'Block',
     loc: null,
     children: List { cursor: null, head: [Object], tail: [Object] } } }
{ type: 'Raw', loc: null, value: 'p, .navbar' }
{ type: 'Block',
  loc: null,
  children:
   List {
     cursor: null,
     head: { prev: null, next: null, data: [Object] },
     tail: { prev: null, next: null, data: [Object] } } }
{ type: 'Declaration',
  loc: null,
  important: false,
  property: 'color',
  value: { type: 'Raw', loc: null, value: ' brown ' } }
{ type: 'Raw', loc: null, value: ' brown ' }
```
Does that help?

**Comment by lahmatiy** [comment] 2017-08-25 12:57
The problem is that `Rule.selector` contains wrong subtree. CSSO expects parsed selector here. You can fix it by AST transformation, like so:
```js
csstree.walk(cleanedAst, function(node) {
  if (node.type === 'Rule' && node.selector.type === 'Raw') {
    node.selector = csstree.parse(node.selector.value, { context: 'selectorList' });
  }
})
```
As I see, declaration values isn't parsed either. It should be fixed too.

---
A couple of tips:
- When you fill issue about an error, would be nice to provide a stack trace
- Use `JSON.stringify(ast, null, 2)` to dump an AST to JSON - it's cleaner for code snippet and can be turned back to AST by `csstree.fromPlainObject()` later

**Comment by peterbe** [comment] 2017-08-25 18:20
Your suggestion did make it work. I didn't need to rehydrate the declaration values actually. It worked anyway. 

What did discover though is that compressing the ast is not really worth it. 

What my script does is that it opens multiple URLs (of HTML). Each one has potentially N .css URLs. What I can do is concatenate them all as one big string and then run `var minifiedCss = csso.minify(combinedCSS).css;` where `combinedCSS` is something like 
```javascript
const combinedCSS = mulitpleAsts.map(ast => csstree.translate(ast)).join('\n')
```
It actually works. 
Now I just need to tidy it all up. 
---

I'm quite familiar with JavaScript in the browser but Node still feels like a fight every time. I didn't get a stack trace. Just that one line. 

Thanks for the tip about `JSON.stringify(ast, null, 2)`!

**Comment by peterbe** [comment] 2017-08-26 02:41
It's a really really rough draft but seems to work: 
https://github.com/peterbe/minimalcss

**Comment by lahmatiy** [comment] 2017-08-28 10:41
Some thoughts:
- It's unclear why you switch off value parsing (`parseValue: false`). CSSO do nothing with values in this case
- No need to do `toPlainObject`/`fromPlainObject`. Those functions are using for export to/from JSON, and just walk through AST and replace List instances for arrays or vice versa. If you need a copy of AST for some reasons, use `csstree.clone()`. You also can parse a CSS right before `cleaner` call
- You can apply `csstree.translate()` for any AST node, so no need for you own translate function (`selectorToString`)
- You can use `csstree.walkRules()` to walk through all Rule and Atrule nodes instead of making your own walker

**Comment by peterbe** [comment] 2017-08-28 11:15
Thanks for the feedback, the reason I use `toPlainObject`/`fromPlainObject` is so I can send the object into the `page.evaluate()` function. You can't send real objects, it has to be a ["Serializable"](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args). Which defaults to the `JSON.stringify` function.

In the same sense that you can't pass objects between a node app and a web browser, you have to kinda print out the object, copy it with the mouse, then start Chrome, start the DevTools console and paste. 

In the same way, I can't pass in a function. So I can't use any of the imported `csstree` module inside the `evaluate` function. 

So I use real objects, package them into serializables, do something with them in the context of `document` and then send them back serialized, and lastly package it back up again. 

An alternative might be to use `page.evaluate` to just return whole HTML as a string payload, then use a HTML parser afterwards in Node. If that'd be the case I wouldn't have to try to do my own silly `selectorToString` stuff.

**Comment by lahmatiy** [comment] 2017-08-28 11:54
Thank you for clarification. I missed the fact that code is running in another context.
Well, you can't use imported csstree instance, but can use csstree bundle still. I'm not sure, but looks like it may be injected via [page.injectFile()](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageinjectfilefilepath). If it works you'll get all csstree API in page context.

**Comment by peterbe** [comment] 2017-08-28 12:44
Awesome! That's another thing for me to try out.

**Closed** 2017-09-10 21:46 UTC
